# This file defines the automated build process on GitHub.
# It has been updated to use the latest version of the upload-artifact action.

name: Build Windows Executable

on:
  push:
    branches: [ "main", "master" ] # Triggers the build on a push to main or master branch
  workflow_dispatch: # Allows you to manually trigger the build

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to v4

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --name "API_Connection_Monitor" main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4 # <<< THIS IS THE FIX (Updated from v3 to v4)
      with:
        name: Windows-Executable
        path: dist/API_Connection_Monitor.exe

